import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pesque Pague Gibicoski</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <Link href="/fishing">Pesque Pague</Link>
      </main>

      <footer className={styles.footer}>
  
      </footer>
    </div>
  )
}
