import Head from 'next/head'
import Link from 'next/link'
// import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pesque Pague Gibicoski</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
        <Link href="/fishing">Pesque Pague</Link>
    </div>
  )
}
