import { GetStaticProps } from 'next';
import Head from 'next/head'
import Image from 'next/image';

import api from '../components/services/axios';

import styles from '../styles/Home.module.scss'

interface IData {
  id: string;
  title: string;
  icon: string;
  url: string;
}

export default function Home({ data }) {
  console.log(data)
  return (
    <main className={styles.container}>
      <Head>
        <title>Pesque Pague Gibicoski</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
       <section className={styles.cards}>
          {data.map(card => {
            return (
              <a href={card.url} className={styles.card} key={card.id}>
            <Image src={card.icon} alt='' height="22" width="22" />
              <span>{card.title}</span>
            </a>
            )
          })} 
       </section>
    </main>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const { data } = await api.get<IData>('/api/data')

  return { 
    props: { data: data }
  }
}