import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Pesqueiro() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Pesque Pague GIBICOSKI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="favicon.png" href="/favicon.png" />
      </Head>

      <main className={styles.main}>
        pesqueiro
      </main>

      <footer className={styles.footer}>
  
      </footer>
    </div>
  )
}
